apiVersion: v1
kind: Service
metadata:
  name: goserver
spec:
  selector:
    app: goserver
  type: LoadBalancer #NodePort  #ClusterIP
  ports:
  - name: goserver
    port: 80
    targetPort: 8080
    #nodePort: 30001  #30000 - 32767 
    protocol: TCP